# Close the dropdown if the user clicks outside of it

### When the user clicks on the button,
toggle between hiding and showing the dropdown content
###

dropdown = ->
  document.getElementById('bMDrop').classList.toggle 'show'
  return

send = ->
  textBox = document.getElementbyId('textArea')
  text = document.getElementById('tBox').value
  textBox.value = textBox.value + text
  return

selectMap = ->
  imageLoader = document.getElementById('theFile')

  handleImage = (e) ->
    reader = new FileReader

    reader.onload = (event) ->
      img = new Image

      img.onload = ->
        canvas.width = img.width
        canvas.height = img.height
        ctx.drawImage img, 0, 0
        return

      img.src = event.target.result
      return

    reader.readAsDataURL e.target.files[0]
    return

  imageLoader.addEventListener 'change', handleImage, false
  canvas = document.getElementById('canvas')
  ctx = canvas.getContext('2d')
  return

handle = (e) ->
  if e.keyCode == 13
    e.preventDefault()
    # Ensure it is only this code that rusn
    textBox = document.getElementById('textArea')
    text = document.getElementById('tBox').value
    textBox.value = textBox.value + text + '\n'
    document.getElementById('tBox').value = ''
  return

diceRoll20 = ->
  profi = parseFloat(document.getElementById('prof').value)
  attrBonus = parseFloat(document.getElementById('attriBonus').value)
  textBox = document.getElementById('textArea')
  base = Math.floor(Math.random() * 20) + 1
  final = base + profi + attrBonus
  text = 'Base Roll: ' + base + ' Final Result: ' + final
  textBox.value = textBox.value + text + '\n'
  return

diceRoll = ->
  attrBonus = parseFloat(document.getElementById('attriBonus').value)
  numDice = parseFloat(document.getElementById('diceN').value)
  numSides = parseFloat(document.getElementById('diceS').value)
  finalDice = 0
  i = 0
  while i < numDice
    finalDice += Math.floor(Math.random() * numSides) + 1
    i++
  final = finalDice + attrBonus
  textBox = document.getElementById('textArea')
  text = '' + numDice + ' d' + numSides + ' = ' + final
  textBox.value = textBox.value + text + '\n'
  return

performClick = (elemId) ->
  elem = document.getElementById(elemId)
  if elem and document.createEvent
    evt = document.createEvent('MouseEvents')
    evt.initEvent 'click', true, false
    elem.dispatchEvent evt
  return

window.onclick = (e) ->
  if !e.target.matches('.dropbtn')
    myDropdown = document.getElementById('bMDrop')
    if myDropdown.classList.contains('show')
      myDropdown.classList.remove 'show'
  return

# ---
# generated by js2coffee 2.2.0